baseURL = 'https://illuminaite-academy.github.io/'
languageCode = 'en-us'
title = 'Illuminaite'
theme = 'illuminaite'

summarylength = 25

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "Home"
url = ""
weight = 1
[[menu.nav]]
name = "About"
url = "about"
weight = 2
[[menu.nav]]
name = "Team"
url = "team"
weight = 3
[[menu.nav]]
name = "Events"
url = "events"
weight = 4
[[menu.nav]]
name = "Blog"
url = "blog"
weight = 5
[[menu.nav]]
name = "Hackathon"
url = "hackathon"
weight = 6
[[menu.nav]]
name = "Contact Us"
url = "contact"
weight = 10

# Site Params
[params]
logo = "images/logo.png"
logo_footer = "images/logo-footer.png"
favicon_shortcut_icon = "images/logo.png"
custom_stylesheets = []                      # [ "scss/my_1.scss", "scss/my_2.scss" ]
dateFormat = "26 FEB 1994"
# Meta data
description = "Illuminaite Academy | Demystifying the world of CS & AI"
author = "Illuminaite Academy"
# Google Analitycs
googleAnalitycsID = "Your ID"
# We're using formspree.io for form handling, paste your formspree url below
fabform = "https://fabform.io/f/USAg2Jl"

# Contact Form
[params.contactForm]
placeholder_first_name = "First Name"
placeholder_last_name = "Last Name"
placeholder_email = "Email"
placeholder_project_type = "Project Type"
placeholder_about_the_project = "About the Project"
send_message = "Send Message"

[[params.contactForm.projectType]]
value = "gd"
title = "Graphics Design"
[[params.contactForm.projectType]]
value = "wd"
title = "Web Design"

# Navbar Action Button
[params.navAction]
status = true
name = "Contact Us"
url = "mailto:illuminaiteacademy@gmail.com"


# Banner Section
[params.banner]
enable = true
heading = "illuminaite academy"
tagline = """
> demystifying the world of CS & AI
<br>> building a network of interdisciplinary <br> students & opportunities
"""
primary_button = "See Our Blog"
primary_button_url = "blog"
secondary_button = "Connect with Us"
secondary_button_url = "mailto:illuminaiteacademy@gmail.com"

[params.blog]
read_more = "read more"

[params.portfolio]
enable = true
title = "OUR RECENT WORKS"
subtitle = "Crafting experiences and seeking to make the complex clear & beautiful."
view_project = "Learn More"
more_works = "MORE WORKS"
scroll_down = "scroll down"

[params.call_to_action]
enable = true
title = "let's work together!"
primary_button = "Contact"
primary_button_url = "contact"
secondary_button = "Join Our Team"
secondary_button_url = "https://forms.gle/L8dgspKPxhLGbYWg8"

[params.footer]
params.footer.qr_print = false
# Footer Contact Info
# [params.footer.contactInfo]
# title = "Contact Info"
# address = "713 Elmwood St.<br>Prior Lake, MN 55372"
# phone = "409-896-1444"
# email = "info@roxo.co"
# Footer Sitemap
[params.footer.sitemap]
title = "Sitemap"
[[params.footer.sitemap.link]]
name = "About Us"
url = "about"
[[params.footer.sitemap.link]]
name = "Events"
url = "events"
[[params.footer.sitemap.link]]
name = "Blog"
url = "blog"
[[params.footer.sitemap.link]]
name = "Contact"
url = "mailto:illuminaiteacademy@gmail.com"
# Footer Social Media
[params.footer.social]
title = "Social Media"
[[params.footer.social.link]]
name = "Instagram"
url = "https://www.instagram.com/illuminaiteacademy/"
[[params.footer.social.link]]
name = "Discord"
url = "https://discord.gg/BjNqZrdSTA"
[[params.footer.social.link]]
name = "Mailing List"
url = "https://forms.gle/29s7EBYi2cprWFER8"
# Footer Service
[params.footer.service]
title = "illuminaite academy"
description = "demystifying the world of CS & AI<br>building a network of interdisciplinary<br>students & opportunities "
[params.footer.back_to_top]
description = "I want to <br> visit again"
